### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by AGeyster** [jhaslowh/UFO_Attack#101]
Whenever I uncomment the include statement in NPC.h to include ScriptHandler.h it crashes every class related to NPC's. 
Because of this I have the method calls for script updating in NPC's ondeath and onabduct commented out as they need to be able to get the scripthandler pointer.

**Comment by AGeyster** [comment]
Unless someone can figure out what is going on there we can limit scripts in the demo to not using death and abductions just gotta edit the script files.

**Comment by jhaslowh** [comment]
Circular dependency, I will try and fix it.
